spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:/test_template_db
  jpa:
    hibernate:
      ddl-auto: update

s3:
  access-key: fake
  secret-key: fake
  endpoint: fake
  region: fake

base:
  url: fake